#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# 1. DYNAMIC ARCHITECTURE & MULTIARCH SYSTEM TRIPLET DETECTION
# Automatically extracts standard Debian tokens (e.g., amd64, arm64, i386)
ARCH=$(dpkg-architecture -qDEB_HOST_ARCH)

# Automatically extracts system library folder triplets (e.g., x86_64-linux-gnu, aarch64-linux-gnu)
TRIPLET=$(dpkg-architecture -qDEB_HOST_MULTIARCH)

VERSION=$(date +%Y.%m.%d)
PKG_NAME="dhewm3"
DIR_NAME="${PKG_NAME}_${VERSION}_${ARCH}"
REPO_URL="https://github.com/dhewm/dhewm3.git"
SOURCE_DIR="dhewm3"

echo "=== Starting packaging process for ${PKG_NAME} on Architecture: ${ARCH} (Triplet: ${TRIPLET}) ==="

# 2. Clone or update the source code repository from GitHub
if [ ! -d "$SOURCE_DIR" ]; then
    echo "-> Cloning dhewm3 source code..."
    git clone "$REPO_URL" "$SOURCE_DIR"
    cd "$SOURCE_DIR"
else
    echo "-> Repository already exists. Pulling latest updates..."
    cd "$SOURCE_DIR"
    git pull
fi

# 3. Configure and Compile using CMake out-of-source build rules
echo "-> Configuring and compiling with CMake..."
rm -rf build
mkdir -p build
cd build
cmake ../neo/
make -j$(nproc)
cd ../.. # Return back to script execution root

# 4. Create the clean staging directory structure (Standard Debian hierarchy matching Multiarch)
echo "-> Creating staging directory structure..."
rm -rf "$DIR_NAME"
mkdir -p "$DIR_NAME/DEBIAN"
mkdir -p "$DIR_NAME/usr/games"
mkdir -p "$DIR_NAME/usr/lib/${TRIPLET}/dhewm3"
mkdir -p "$DIR_NAME/usr/share/games/doom3/base"
mkdir -p "$DIR_NAME/usr/share/games/doom3/d3xp"
mkdir -p "$DIR_NAME/usr/share/applications"

# 5. Copy natively compiled binaries and dynamic game libraries into architecture-specific paths
echo "-> Copying natively compiled binaries and libraries..."
if [ -f "$SOURCE_DIR/build/dhewm3" ]; then
    # CRITICAL: Binary and game libraries must live in the identical triplet directory for security checks to pass!
    cp "$SOURCE_DIR/build/dhewm3" "$DIR_NAME/usr/lib/${TRIPLET}/dhewm3/"
    
    if [ -f "$SOURCE_DIR/build/dhewm3ded" ]; then
        cp "$SOURCE_DIR/build/dhewm3ded" "$DIR_NAME/usr/lib/${TRIPLET}/dhewm3/"
        # Create multiarch-aware symbolic pointer link for the dedicated server
        ln -s /usr/lib/${TRIPLET}/dhewm3/dhewm3ded "$DIR_NAME/usr/games/dhewm3ded"
    fi
    
    # Copy across the natively built core game libraries generated by CMake into system triplet path
    if [ -f "$SOURCE_DIR/build/base.so" ]; then
        cp "$SOURCE_DIR/build/base.so" "$DIR_NAME/usr/lib/${TRIPLET}/dhewm3/"
    fi
    if [ -f "$SOURCE_DIR/build/d3xp.so" ]; then
        cp "$SOURCE_DIR/build/d3xp.so" "$DIR_NAME/usr/lib/${TRIPLET}/dhewm3/"
    fi
    
    # Create the global user binary symlink targeting the triplet location
    ln -s /usr/lib/${TRIPLET}/dhewm3/dhewm3 "$DIR_NAME/usr/games/dhewm3"
else
    echo "Error: Compiled binary 'dhewm3' not detected inside the build/ layout root."
    exit 1
fi

# 6. Create the desktop shortcut launcher file dynamically passing system data folder parameters
echo "-> Creating desktop shortcut..."
cat << EOF > "$DIR_NAME/usr/share/applications/dhewm3.desktop"
[Desktop Entry]
Name=dhewm3
Comment=Doom 3 Source Port
Exec=/usr/games/dhewm3 +set fs_basepath /usr/share/games/doom3
Terminal=false
Type=Application
Icon=applications-games
Categories=Game;ActionGame;
EOF

# 7. Generate the Debian control file dynamically with the version, detected architecture, and Multi-Arch flags
echo "-> Generating metadata control file..."
cat << EOF > "$DIR_NAME/DEBIAN/control"
Package: ${PKG_NAME}
Version: ${VERSION}
Section: games
Priority: optional
Architecture: ${ARCH}
Multi-Arch: same
License: GPL-3.0-or-later
Maintainer: EQLinux <https://github.com/eqvaldi>
Depends: libsdl2-2.0-0, libopenal1, libcurl4, libgl1
Description: dhewm3 engine port for Doom 3 (Multiarch Build)
 dhewm3 is a Doom 3 GPL source port optimized to work seamlessly
 on modern systems using SDL2 and OpenAL.
 Automatically detected, compiled, and packaged for ${ARCH} architectures.
 Automatically packaged on $(date +%Y-%m-%d).
EOF

# 8. Generate the official system copyright metadata file tracking the GPLv3 license precisely
echo "-> Generating system copyright tracking documentation..."
mkdir -p "$DIR_NAME/usr/share/doc/${PKG_NAME}"
cat << EOF > "$DIR_NAME/usr/share/doc/${PKG_NAME}/copyright"
Format: https://debian.org
Upstream-Name: dhewm3
Source: ${REPO_URL}

Files: *
Copyright: 2004-2011 id Software, Inc.
           2011-2026 Daniel Gibson and the dhewm3 contributors
License: GPL-3.0-or-later
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 .
 On Debian systems, the complete text of the GNU General Public
 License version 3 can be found in "/usr/share/common-licenses/GPL-3".
EOF

# 9. Build the final .deb package safely ensuring root ownership
echo "-> Building the Debian package..."
dpkg-deb --root-owner-group --build "$DIR_NAME"

# 10. Clean up the staging directory structure
rm -rf "$DIR_NAME"

echo "=== Success! Package built: ${DIR_NAME}.deb ==="
