#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# 1. Define variables and dynamic rolling date-based version
VERSION=$(date +%Y.%m.%d)
ARCH="amd64"
PKG_NAME="dhewm3"
DIR_NAME="${PKG_NAME}_${VERSION}_${ARCH}"
REPO_URL="https://github.com/dhewm/dhewm3.git"
SOURCE_DIR="dhewm3"

echo "=== Starting packaging process for ${PKG_NAME} version ${VERSION} ==="

# 2. Clone or update the source code repository from GitHub
if [ ! -d "$SOURCE_DIR" ]; then
    echo "-> Cloning dhewm3 source code..."
    git clone "$REPO_URL" "$SOURCE_DIR"
    cd "$SOURCE_DIR"
else
    echo "-> Repository already exists. Pulling latest updates..."
    cd "$SOURCE_DIR"
    git pull
fi

# 3. Configure and Compile using CMake out-of-source build rules
echo "-> Configuring and compiling with CMake..."
rm -rf build
mkdir -p build
cd build
cmake ../neo/
make -j$(nproc)
cd ../.. # Return back to script execution root

# 4. Create the clean staging directory structure (Standard Debian hierarchy)
echo "-> Creating staging directory structure..."
rm -rf "$DIR_NAME"
mkdir -p "$DIR_NAME/DEBIAN"
mkdir -p "$DIR_NAME/usr/games"
mkdir -p "$DIR_NAME/usr/lib/dhewm3"
mkdir -p "$DIR_NAME/usr/share/games/doom3/base"
mkdir -p "$DIR_NAME/usr/share/games/doom3/d3xp"
mkdir -p "$DIR_NAME/usr/share/applications"

# 5. Copy natively compiled binaries and dynamic game libraries into packaging staging
echo "-> Copying natively compiled binaries and libraries..."
if [ -f "$SOURCE_DIR/build/dhewm3" ]; then
    # CRITICAL: Binary and libraries must live in the exact same directory for security check to pass!
    cp "$SOURCE_DIR/build/dhewm3" "$DIR_NAME/usr/lib/dhewm3/"
    
    if [ -f "$SOURCE_DIR/build/dhewm3ded" ]; then
        cp "$SOURCE_DIR/build/dhewm3ded" "$DIR_NAME/usr/lib/dhewm3/"
        ln -s /usr/lib/dhewm3/dhewm3ded "$DIR_NAME/usr/games/dhewm3ded"
    fi
    
    # Copy across the natively built core game libraries generated by CMake into system path
    if [ -f "$SOURCE_DIR/build/base.so" ]; then
        cp "$SOURCE_DIR/build/base.so" "$DIR_NAME/usr/lib/dhewm3/"
    fi
    if [ -f "$SOURCE_DIR/build/d3xp.so" ]; then
        cp "$SOURCE_DIR/build/d3xp.so" "$DIR_NAME/usr/lib/dhewm3/"
    fi
    
    # Create the global binary symlink for users
    ln -s /usr/lib/dhewm3/dhewm3 "$DIR_NAME/usr/games/dhewm3"
else
    echo "Error: Compiled binary 'dhewm3' not detected inside the build/ layout root."
    exit 1
fi

# 6. Create the desktop shortcut launcher file dynamically passing system data folder parameters
echo "-> Creating desktop shortcut..."
cat << EOF > "$DIR_NAME/usr/share/applications/dhewm3.desktop"
[Desktop Entry]
Name=dhewm3
Comment=Doom 3 Source Port
Exec=/usr/games/dhewm3 +set fs_basepath /usr/share/games/doom3
Terminal=false
Type=Application
Icon=applications-games
Categories=Game;ActionGame;
EOF

# 7. Generate the Debian control file dynamically with the live version stamp
echo "-> Generating metadata control file..."
cat << EOF > "$DIR_NAME/DEBIAN/control"
Package: ${PKG_NAME}
Version: ${VERSION}
Section: games
Priority: optional
Architecture: ${ARCH}
Provides: doom-engine
Maintainer: EQLinux <https://github.com/eqvaldi>
Depends: libsdl2-2.0-0, libopenal1, libcurl4, libgl1
Description: dhewm3 engine port for Doom 3
 dhewm3 is a Doom 3 GPL source port optimized to work seamlessly
 on modern 64-bit systems using SDL2 and OpenAL.
 Automatically packaged on $(date +%Y-%m-%d).
EOF

# 8. Build the final .deb package safely ensuring root ownership
echo "-> Building the Debian package..."
dpkg-deb --root-owner-group --build "$DIR_NAME"

# 9. Clean up the staging directory structure
rm -rf "$DIR_NAME"

echo "=== Success! Package built: ${DIR_NAME}.deb ==="
