#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# 1. DYNAMIC ARCHITECTURE & MULTIARCH SYSTEM TRIPLET DETECTION
# Automatically extracts standard Debian tokens (e.g., amd64, arm64, i386)
ARCH=$(dpkg-architecture -qDEB_HOST_ARCH)

# Automatically extracts system library folder triplets (e.g., x86_64-linux-gnu, aarch64-linux-gnu)
TRIPLET=$(dpkg-architecture -qDEB_HOST_MULTIARCH)

VERSION=$(date +%Y.%m.%d)
PKG_NAME="ioquake3"
DIR_NAME="${PKG_NAME}_${VERSION}_${ARCH}"
REPO_URL="https://github.com/ioquake/ioq3.git"
SOURCE_DIR="ioq3"

echo "=== Starting packaging process for ${PKG_NAME} on Architecture: ${ARCH} (Triplet: ${TRIPLET}) ==="

# 2. Clone or update the engine source code repository
if [ ! -d "$SOURCE_DIR" ]; then
    echo "-> Cloning ioquake3 source code..."
    git clone "$REPO_URL" "$SOURCE_DIR"
    cd "$SOURCE_DIR"
else
    echo "-> Repository already exists. Pulling latest updates..."
    cd "$SOURCE_DIR"
    git pull
fi

# 3. Configure workspace meta-blueprints and compile targets
echo "-> Formatting build directories via CMake..."
cmake ./
echo "-> Compiling core client and dedicated server binaries with $(nproc) threads..."
make -j$(nproc)
cd .. # Return back to script execution root

# 4. Create the clean staging directory structure targeting Multiarch pathways
echo "-> Creating staging directory structure..."
rm -rf "$DIR_NAME"
mkdir -p "$DIR_NAME/DEBIAN"
mkdir -p "$DIR_NAME/usr/games"
mkdir -p "$DIR_NAME/usr/lib/${TRIPLET}/ioquake3/baseq3"
mkdir -p "$DIR_NAME/usr/share/applications"

# 5. Copy the compiled binaries and modular renderer components into architecture staging
echo "-> Copying executable targets and architecture binaries from Release/..."
if [ -f "$SOURCE_DIR/Release/ioquake3" ]; then
    # Install main client binary to architecture-specific triplet library path context
    cp "$SOURCE_DIR/Release/ioquake3" "$DIR_NAME/usr/lib/${TRIPLET}/ioquake3/ioquake3-bin"
    
    # Dedicated server remains globally linkable or routed alongside libraries
    cp "$SOURCE_DIR/Release/ioq3ded" "$DIR_NAME/usr/lib/${TRIPLET}/ioquake3/ioq3ded-bin"
    ln -s /usr/lib/${TRIPLET}/ioquake3/ioq3ded-bin "$DIR_NAME/usr/games/ioq3ded"
    
    # Copy library-level modular renderer extensions (.so drivers) directly into the triplet library root
    cp "$SOURCE_DIR"/Release/renderer_opengl*.so "$DIR_NAME/usr/lib/${TRIPLET}/ioquake3/" 2>/dev/null || true
    
    # Copy baseline game logic binaries if generated by the CMake configuration
    if [ -f "$SOURCE_DIR/Release/baseq3/cgame.so" ]; then
        cp "$SOURCE_DIR"/Release/baseq3/*.so "$DIR_NAME/usr/lib/${TRIPLET}/ioquake3/baseq3/" 2>/dev/null || true
    fi
else
    echo "Error: Compiled engine binaries not detected in $SOURCE_DIR/Release/"
    exit 1
fi

# 6. Create a smart multiarch startup script wrapper that handles home data folder setup safely
echo "-> Creating application launcher wrapper with home directory mapping..."
cat << 'EOF' > "$DIR_NAME/usr/games/ioquake3"
#!/bin/bash
# 1. Ensure the user's custom home folder layout exists for base game assets and custom mods
mkdir -p "$HOME/.ioquake3/baseq3"

# 2. Dynamically determine the machine's active multiarch triplet path at runtime
TRIPLET=$(dpkg-architecture -qDEB_HOST_MULTIARCH)

# 3. Automatically link your architecture-specific libraries natively into your home folder context
ln -sf /usr/lib/${TRIPLET}/ioquake3/renderer_opengl1.so "$HOME/.ioquake3/renderer_opengl1.so"
ln -sf /usr/lib/${TRIPLET}/ioquake3/renderer_opengl2.so "$HOME/.ioquake3/renderer_opengl2.so"
if [ -d /usr/lib/${TRIPLET}/ioquake3/baseq3 ]; then
    ln -sf /usr/lib/${TRIPLET}/ioquake3/baseq3/*.so "$HOME/.ioquake3/baseq3/" 2>/dev/null || true
fi

# 4. Launch the engine, explicitly setting the user home directory as the system game assets basepath
exec /usr/lib/${TRIPLET}/ioquake3/ioquake3-bin +set fs_homepath "$HOME/.ioquake3" +set fs_basepath "$HOME/.ioquake3" "$@"
EOF
chmod 755 "$DIR_NAME/usr/games/ioquake3"

# 7. Create the desktop shortcut launcher file dynamically pointing straight to your wrapper tool
echo "-> Creating desktop shortcut..."
cat << EOF > "$DIR_NAME/usr/share/applications/ioquake3.desktop"
[Desktop Entry]
Name=ioquake3
Comment=Community Quake III Arena Engine Evolution
Exec=/usr/games/ioquake3
Terminal=false
Type=Application
Icon=applications-games
Categories=Game;ActionGame;
EOF

# 8. Generate the Debian control file dynamically with the live version, architecture, and Multi-Arch fields
echo "-> Generating metadata control file..."
cat << EOF > "$DIR_NAME/DEBIAN/control"
Package: ${PKG_NAME}
Version: ${VERSION}
Section: games
Priority: optional
Architecture: ${ARCH}
Multi-Arch: same
License: GPL-2.0-or-later
Maintainer: EQLinux <https://github.com/eqvaldi>
Depends: libsdl2-2.0-0, libopenal1, libcurl4, libjpeg62-turbo, libgl1
Description: ioquake3 engine port for Quake III Arena (Multiarch Build)
 ioquake3 is the premier community-driven engine overhaul for id Software's 
 Quake III Arena, supporting modern platforms, SDL2, and OpenAL.
 Automatically detected, compiled, and packaged for ${ARCH} architectures.
 Automatically packaged on $(date +%Y-%m-%d).
EOF

# 9. Generate the official system copyright metadata file tracking the GPLv2 license precisely
echo "-> Generating system copyright tracking documentation..."
mkdir -p "$DIR_NAME/usr/share/doc/${PKG_NAME}"
cat << EOF > "$DIR_NAME/usr/share/doc/${PKG_NAME}/copyright"
Format: https://debian.org
Upstream-Name: ioquake3
Source: ${REPO_URL}

Files: *
Copyright: 1999-2005 id Software, Inc.
           2005-2026 The ioquake3 contributors
License: GPL-2.0-or-later
 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; version 2 of the License.
 .
 On Debian systems, the complete text of the GNU General Public
 License version 2 can be found in "/usr/share/common-licenses/GPL-2".
EOF

# 10. Build the final .deb package safely ensuring root ownership
echo "-> Building the Debian package..."
dpkg-deb --root-owner-group --build "$DIR_NAME"

# 11. Clean up the staging directory structure
rm -rf "$DIR_NAME"

echo "=== Success! Package built: ${DIR_NAME}.deb ==="
